#Camera
CAMERA_INDEX = 0
CAMERA_WIDTH = 640
CAMERA_HEIGHT = 480
FPS_TARGET = 30

#MediaPipe
MAX_HANDS = 2
DETECTION_CONFIDENCE = 0.7
TRACKING_CONFIDENCE = 0.7

#Gesture Thresholds
FIST_THRESHOLD = 0.15
PINCH_THRESHOLD = 0.08

#Phone Screen (dafault, will be overwritten by calibration)
PHONE_WIDTH = 1080
PHONE_HEIGHT = 1920

#ADB
ADB_SWIPE_DURATION = 50
